
[functions.resend]
enabled = true
verify_jwt = false
import_map = "./functions/resend/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/resend/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/resend/*.html" ]

[functions.weekly-contact-test]
enabled = true
verify_jwt = true
import_map = "./functions/weekly-contact-test/deno.json"
entrypoint = "./functions/weekly-contact-test/index.ts"